/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : GPIO1.c
**     Project     : wolf
**     Processor   : MKE04Z128VLD4
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.08, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-12-20, 02:33, # CodeGen: 0
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : GPIO1
**          Port                                           : GPIOA
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 0xFFE7FFC3
**          Interrupt service/event                        : Disabled
**          Bit fields                                     : 6
**            Bit field                                    : 
**              Field name                                 : IO_DATA
**              Pins                                       : 8
**                Pin                                      : 
**                  Pin                                    : PTD0/KBI0_P24/FTM2_CH2/SPI1_SCK
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTD1/KBI0_P25/FTM2_CH3/SPI1_MOSI
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTD2/KBI0_P26/SPI1_MISO
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTD3/KBI0_P27/SPI1_PCS
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTD4/KBI0_P28
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTD5/KBI0_P29/PWT_IN0
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTD6/KBI0_P30/UART2_RX
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTD7/KBI0_P31/UART2_TX
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : IO_ADDR
**              Pins                                       : 13
**                Pin                                      : 
**                  Pin                                    : PTA6/KBI0_P6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTA7/KBI0_P7/FTM2_FLT2/ACMP1_IN1/ADC0_SE3
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB0/KBI0_P8/UART0_RX/PWT_IN1/ADC0_SE4
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB1/KBI0_P9/UART0_TX/ADC0_SE5
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB2/KBI0_P10/SPI0_SCK/FTM0_CH0/ADC0_SE6
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB3/KBI0_P11/SPI0_MOSI/FTM0_CH1/ADC0_SE7
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB4/KBI0_P12/FTM2_CH4/SPI0_MISO/ACMP1_IN2/NMI_b
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB5/KBI0_P13/FTM2_CH5/SPI0_PCS/ACMP1_OUT
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB6/KBI0_P14/I2C0_SDA/XTAL
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTB7/KBI0_P15/I2C0_SCL/EXTAL
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTC0/KBI0_P16/FTM2_CH0/ADC0_SE8
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTC1/KBI0_P17/FTM2_CH1/ADC0_SE9
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTC2/KBI0_P18/FTM2_CH2/ADC0_SE10
**                  Initial pin direction                  : Output
**                    Initial output state                 : 0
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : IO_OE
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC5/KBI0_P21/FTM1_CH1/RTCO
**                  Initial pin direction                  : Output
**                    Initial output state                 : 1
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : IO_RW
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC6/KBI0_P22/UART1_RX
**                  Initial pin direction                  : Output
**                    Initial output state                 : 1
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : IO_CE
**              Pins                                       : 1
**                Pin                                      : 
**                  Pin                                    : PTC7/KBI0_P23/UART1_TX
**                  Initial pin direction                  : Output
**                    Initial output state                 : 1
**                  Initial pin event                      : Disabled
**            Bit field                                    : 
**              Field name                                 : IO_EA
**              Pins                                       : 2
**                Pin                                      : 
**                  Pin                                    : PTA0/KBI0_P0/FTM0_CH0/I2C0_4WSCLOUT/ACMP0_IN0/ADC0_SE0
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**                Pin                                      : 
**                  Pin                                    : PTA1/KBI0_P1/FTM0_CH1/I2C0_4WSDAOUT/ACMP0_IN1/ADC0_SE1
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**          Initialization                                 : 
**            Auto initialization                          : yes
**            Event mask                                   : 
**              OnPortEvent                                : Disabled
**     Contents    :
**         Init                    - LDD_TDeviceData* GPIO1_Init(LDD_TUserData *UserDataPtr);
**         SetFieldValue           - void GPIO1_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField...
**         GetFieldValue           - GPIO1_TFieldValue GPIO1_GetFieldValue(LDD_TDeviceData *DeviceDataPtr,...
**         SetFieldInputDirection  - void GPIO1_SetFieldInputDirection(LDD_TDeviceData *DeviceDataPtr,...
**         SetFieldOutputDirection - void GPIO1_SetFieldOutputDirection(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file GPIO1.c
** @version 01.08
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup GPIO1_module GPIO1 module documentation
**  @{
*/         

/* MODULE GPIO1. */

#include "GPIO1.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  LDD_TUserData *UserData;             /* RTOS device data structure */
} GPIO1_TDeviceData, *GPIO1_TDeviceDataPtr; /* Device data structure type */
/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static GPIO1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/*
** ===================================================================
**     Method      :  GPIO1_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* GPIO1_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  GPIO1_TDeviceData *DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Save RTOS Device structure */
  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */
  /* GPIOA_PDOR: PDO&=~0x0007FFC0,PDO|=0x00E00000 */
  GPIOA_PDOR = (uint32_t)((GPIOA_PDOR & (uint32_t)~(uint32_t)(
                GPIO_PDOR_PDO(0x0007FFC0)
               )) | (uint32_t)(
                GPIO_PDOR_PDO(0x00E00000)
               ));
  /* GPIOA_PIDR: PID&=~0xFF000003 */
  GPIOA_PIDR &= (uint32_t)~(uint32_t)(GPIO_PIDR_PID(0xFF000003));
  /* GPIOA_PDDR: PDD&=~0xFF000003,PDD|=0x00E7FFC0 */
  GPIOA_PDDR = (uint32_t)((GPIOA_PDDR & (uint32_t)~(uint32_t)(
                GPIO_PDDR_PDD(0xFF000003)
               )) | (uint32_t)(
                GPIO_PDDR_PDD(0x00E7FFC0)
               ));
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_GPIO1_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  GPIO1_SetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the output data value of the specified bit
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Value           - Aligned data value to writting to the
**                           specified bit field. The bit 0 corresponds
**                           with the pin which has index 0 within the
**                           given bit field, the bit 1 corresponds with
**                           the pin which has index 1 within the given
**                           bit field, etc.
*/
/* ===================================================================*/
void GPIO1_SetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPIO1_TFieldValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case IO_DATA: {                    /* bit field #0 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(~((GPIO1_TPortValue)GPIO1_IO_DATA_MASK)))
        )
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_DATA_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_DATA_MASK)
        )
      );
      break;
    }
    case IO_ADDR: {                    /* bit field #1 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(~((GPIO1_TPortValue)GPIO1_IO_ADDR_MASK)))
        )
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_ADDR_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_ADDR_MASK)
        )
      );
      break;
    }
    case IO_OE: {                      /* bit field #2 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(~((GPIO1_TPortValue)GPIO1_IO_OE_MASK)))
        )
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_OE_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_OE_MASK)
        )
      );
      break;
    }
    case IO_RW: {                      /* bit field #3 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(~((GPIO1_TPortValue)GPIO1_IO_RW_MASK)))
        )
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_RW_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_RW_MASK)
        )
      );
      break;
    }
    case IO_CE: {                      /* bit field #4 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(~((GPIO1_TPortValue)GPIO1_IO_CE_MASK)))
        )
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_CE_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_CE_MASK)
        )
      );
      break;
    }
    case IO_EA: {                      /* bit field #5 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        (
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(~((GPIO1_TPortValue)GPIO1_IO_EA_MASK)))
        )
        | (
          Value
          & ((GPIO1_TPortValue)GPIO1_IO_EA_MASK)
        )
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPIO1_GetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current input data of the specified
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to reading. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @return
**                         - Aligned current port input value masked for
**                           allocated pins of the field. The bit 0
**                           corresponds with the pin which has index 0
**                           within the given bit field, the bit 1
**                           corresponds with the pin which has index 1
**                           within the given bit field, etc.
*/
/* ===================================================================*/
GPIO1_TFieldValue GPIO1_GetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case IO_DATA: {                    /* bit field #0 */
      return
        (GPIO1_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPIO1_MODULE_BASE_ADDRESS)
            & (GPIO1_TPortValue)GPIO1_IO_DATA_MASK
          )
          >> GPIO1_IO_DATA_START_BIT
        );
    }
    case IO_ADDR: {                    /* bit field #1 */
      return
        (GPIO1_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPIO1_MODULE_BASE_ADDRESS)
            & (GPIO1_TPortValue)GPIO1_IO_ADDR_MASK
          )
          >> GPIO1_IO_ADDR_START_BIT
        );
    }
    case IO_OE: {                      /* bit field #2 */
      return
        (GPIO1_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPIO1_MODULE_BASE_ADDRESS)
            & (GPIO1_TPortValue)GPIO1_IO_OE_MASK
          )
          >> GPIO1_IO_OE_START_BIT
        );
    }
    case IO_RW: {                      /* bit field #3 */
      return
        (GPIO1_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPIO1_MODULE_BASE_ADDRESS)
            & (GPIO1_TPortValue)GPIO1_IO_RW_MASK
          )
          >> GPIO1_IO_RW_START_BIT
        );
    }
    case IO_CE: {                      /* bit field #4 */
      return
        (GPIO1_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(GPIO1_MODULE_BASE_ADDRESS)
            & (GPIO1_TPortValue)GPIO1_IO_CE_MASK
          )
          >> GPIO1_IO_CE_START_BIT
        );
    }
    case IO_EA: {                      /* bit field #5 */
      return
        (GPIO1_TFieldValue)(
          GPIO_PDD_GetPortDataInput(GPIO1_MODULE_BASE_ADDRESS)
          & (GPIO1_TPortValue)GPIO1_IO_EA_MASK
        );
    }
    default:
      break;                           /* Invalid BitField is not treated, result is undefined */
  } /* switch (Field) */
  return (GPIO1_TFieldValue)0U;
}

/*
** ===================================================================
**     Method      :  GPIO1_SetFieldInputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets all pins of the field to the input
**         direction.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
*/
/* ===================================================================*/
void GPIO1_SetFieldInputDirection(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case IO_DATA: {                    /* bit field #0 */
      GPIO_PDD_SetPortInputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_DATA_MASK
      );
      break;
    }
    case IO_ADDR: {                    /* bit field #1 */
      GPIO_PDD_SetPortInputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_ADDR_MASK
      );
      break;
    }
    case IO_OE: {                      /* bit field #2 */
      GPIO_PDD_SetPortInputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_OE_MASK
      );
      break;
    }
    case IO_RW: {                      /* bit field #3 */
      GPIO_PDD_SetPortInputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_RW_MASK
      );
      break;
    }
    case IO_CE: {                      /* bit field #4 */
      GPIO_PDD_SetPortInputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_CE_MASK
      );
      break;
    }
    case IO_EA: {                      /* bit field #5 */
      GPIO_PDD_SetPortInputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_EA_MASK
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  GPIO1_SetFieldOutputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets all pins of the field to the output
**         direction.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to set to the output
**                           direction. Bit fields are defined during
**                           design time and for each bit field there is
**                           a generated constant.
**     @param
**         Value           - Aligned data value to appear on the
**                           bit field pins after they have been
**                           switched to the output direction.
*/
/* ===================================================================*/
void GPIO1_SetFieldOutputDirection(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, GPIO1_TFieldValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case IO_DATA: {                    /* bit field #0 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        ((GPIO1_TPortValue)(
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(
            ~((GPIO1_TPortValue)GPIO1_IO_DATA_MASK)
          ))
        ))
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_DATA_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_DATA_MASK)
        )
      );
      GPIO_PDD_SetPortOutputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_DATA_MASK
      );
      break;
    }
    case IO_ADDR: {                    /* bit field #1 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        ((GPIO1_TPortValue)(
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(
            ~((GPIO1_TPortValue)GPIO1_IO_ADDR_MASK)
          ))
        ))
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_ADDR_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_ADDR_MASK)
        )
      );
      GPIO_PDD_SetPortOutputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_ADDR_MASK
      );
      break;
    }
    case IO_OE: {                      /* bit field #2 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        ((GPIO1_TPortValue)(
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(
            ~((GPIO1_TPortValue)GPIO1_IO_OE_MASK)
          ))
        ))
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_OE_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_OE_MASK)
        )
      );
      GPIO_PDD_SetPortOutputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_OE_MASK
      );
      break;
    }
    case IO_RW: {                      /* bit field #3 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        ((GPIO1_TPortValue)(
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(
            ~((GPIO1_TPortValue)GPIO1_IO_RW_MASK)
          ))
        ))
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_RW_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_RW_MASK)
        )
      );
      GPIO_PDD_SetPortOutputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_RW_MASK
      );
      break;
    }
    case IO_CE: {                      /* bit field #4 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        ((GPIO1_TPortValue)(
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(
            ~((GPIO1_TPortValue)GPIO1_IO_CE_MASK)
          ))
        ))
        | (
          ((GPIO1_TPortValue)(Value << GPIO1_IO_CE_START_BIT))
          & ((GPIO1_TPortValue)GPIO1_IO_CE_MASK)
        )
      );
      GPIO_PDD_SetPortOutputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_CE_MASK
      );
      break;
    }
    case IO_EA: {                      /* bit field #5 */
      GPIO_PDD_SetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS,
        ((GPIO1_TPortValue)(
          GPIO_PDD_GetPortDataOutput(GPIO1_MODULE_BASE_ADDRESS)
          & ((GPIO1_TPortValue)(
            ~((GPIO1_TPortValue)GPIO1_IO_EA_MASK)
          ))
        ))
        | (
          Value
          & ((GPIO1_TPortValue)GPIO1_IO_EA_MASK)
        )
      );
      GPIO_PDD_SetPortOutputDirectionMask(GPIO1_MODULE_BASE_ADDRESS,
        GPIO1_IO_EA_MASK
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/* END GPIO1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
